version: '3.8'

services:
  api:
    container_name: numeri-api
    build:
      context: .
      secrets:
        - npm_token
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    container_name: numeri-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

secrets:
  npm_token:
    file: ~/.npm_token
