name: Deploy to Ionos Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Ionos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.IONOS_SSH_PRIVATE_KEY }}

      - name: Deploy to Ionos server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd /var/www/numeri-api
          git pull
          npm ci
          npm run build
          pm2 restart numeri-api
          EOF
